language: python

python:
    - "3.5"
    - "3.6"

install:
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
    - python setup.py install

script:
    - flake8
    - py.test
